<head><meta charset="utf-8" /><title>Cómo manejar excepciones personalizadas en Clojure – Resuelto</title><link href="../styles.css" rel="stylesheet" /><meta content="initial-scale=1, width=device-width" name="viewport" /><link href="https://fonts.googleapis.com" rel="preconnect" /><link crossorigin="crossorigin" href="https://fonts.gstatic.com" rel="preconnect" /><link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:ital,wght@0,100..700;1,100..700&amp;family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&amp;display=swap" rel="stylesheet" /></head><body><noscript>Clojure-tutorials is a JavaScript app. Please enable JavaScript to
      continue.</noscript><div id="app"></div><main><article><h2>Cómo manejar excepciones personalizadas en Clojure – Resuelto</h2><p>En Clojure, podemos definir nuestras propias excepciones para situaciones específicas mediante la creación de excepciones personalizadas.</p>
         <h2>Definir una excepción personalizada</h2>
         <p>Para crear una excepción personalizada, podemos usar <code>ex-info</code>, que nos permite asociar datos adicionales con la excepción.</p>
         <code>(throw (ex-info "Error personalizado" {:tipo :excepcion-especial}))</code></article></main><script src="/js/compiled/app.js"></script></body>